import { useState } from 'react';
import CpuSimulatorViewer from './viewers/CpuSimulatorViewer';
import TraceViewer from './viewers/TraceViewer';
import AirViewer from './viewers/AirViewer';
import PolynomialViewer from './viewers/PolynomialViewer';
import FriViewer from './viewers/FriViewer';
import ProofViewer from './viewers/ProofViewer';

const TABS = [
  { id: 'cpu', label: 'CPU simulator', component: CpuSimulatorViewer },
  { id: 'trace', label: 'Execution trace', component: TraceViewer },
  { id: 'air', label: 'AIR', component: AirViewer },
  { id: 'poly', label: 'Polynomial', component: PolynomialViewer },
  { id: 'fri', label: 'FRI', component: FriViewer },
  { id: 'proof', label: 'Proof explorer', component: ProofViewer },
] as const;

export default function App() {
  const [activeId, setActiveId] = useState<(typeof TABS)[number]['id']>('cpu');
  const Active = TABS.find((t) => t.id === activeId)!.component;

  return (
    <div className="app">
      <header className="app-header">
        <h1>zkvm — interactive STARK visualizers</h1>
        <p>
          Phase 8: six windows into the same pipeline built in Phases 0–7, reading real JSON
          artifacts exported by viz-export — not mocked data.
        </p>
      </header>

      <nav className="tabs">
        {TABS.map((tab) => (
          <button
            key={tab.id}
            className={tab.id === activeId ? 'active' : ''}
            onClick={() => setActiveId(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      <Active />

      <p className="footer-note">
        Artifacts are static JSON, regenerated by running <code>cargo run -p viz-export --bin export</code>{' '}
        from the repo root. Phase 9 will replace this with a live, in-browser prover via WASM.
      </p>
    </div>
  );
}
